### ISSUE TITLE
Mac OS X installation

### ISSUE THREAD

**Issue by npenzin** [MagicStack/uvloop#11]
Requires `brew install libtool` because of `autogen.sh: line 43: glibtoolize: command not found`

**Comment by 1st1** [comment]
You're trying to build uvloop manually, right?

**Comment by digitaldavenyc** [comment]
Also having an issue install on OSX

When running `$ make` I receive this error.
```
subprocess.CalledProcessError: Command '['/bin/sh', 'autogen.sh']' returned non-zero exit status 127
make: *** [compile] Error 1
```

I tried installing `libtool` as well but the error still persists. If there are libraries required for OSX install, I think a README update would be helpful.

**Comment by dabeaz** [comment]
sudo ln -s /usr/local/bin/libtoolize /usr/local/bin/glibtoolize

**Comment by digitaldavenyc** [comment]
@dabeaz `glibtoolize` already exists, probably from installing `libtool`

**Comment by dabeaz** [comment]
That, I don't know.  I didn't get glibtoolize from installing libtool.  Adding the symlink fixed it.  uvloop seems to work on OSX.

**Comment by digitaldavenyc** [comment]
Perhaps I already had it install from another application. Doesn't fix the issue for me either way...

**Comment by 1st1** [comment]
@digitaldavenyc Are you trying to build uvloop manually, or it's a fail of `pip install`?

I think I can repackage the sdist to include a generated Makefile.

**Comment by digitaldavenyc** [comment]
@1st1 I've tried both pip and manually and they both return the same error above

**Comment by digitaldavenyc** [comment]
```
(env)LOSX-339619-DM-N:uvloop digitaldave$ make
rm -fr dist/
rm -fr uvloop/*.c uvloop/*.html uvloop/*.so build *.egg-info
rm -fr uvloop/handles/*.html uvloop/includes/*.html
find . -name '__pycache__' | xargs rm -rf
echo "DEF DEBUG = 0" > uvloop/__debug.pxi
cython -3 uvloop/loop.pyx; rm uvloop/__debug.*
/bin/sh: cython: command not found
python setup.py build_ext --inplace
running build_ext
autogen.sh: line 28: automake: command not found
autogen.sh: line 33: test: : integer expression expected
autogen.sh: line 34: test: : integer expression expected
+ glibtoolize --copy
+ aclocal -I m4
autogen.sh: line 44: aclocal: command not found
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    include_package_data=True
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Volumes/Data/Users/dpadovano/.virtualenvs/tran/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
    _build_ext.run(self)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "setup.py", line 38, in build_extensions
    self.build_libuv()
  File "setup.py", line 31, in build_libuv
    check=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/bin/sh', 'autogen.sh']' returned non-zero exit status 127
make: *** [compile] Error 1
```

**Comment by digitaldavenyc** [comment]
```
(env)LOSX-339619-DM-N:uvloop digitaldave$ pip install uvloop
Collecting uvloop
  Using cached uvloop-0.4.11.tar.gz
Building wheels for collected packages: uvloop
  Running setup.py bdist_wheel for uvloop ... error
  Complete output from command /Volumes/Data/Users/dpadovano/.virtualenvs/tran/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/tmpuuvyv4topip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.10-x86_64-3.5
  creating build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/__init__.py -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/_testbase.py -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  running egg_info
  writing dependency_links to uvloop.egg-info/dependency_links.txt
  writing top-level names to uvloop.egg-info/top_level.txt
  writing uvloop.egg-info/PKG-INFO
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'uvloop.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'uvloop.egg-info/SOURCES.txt'
  copying uvloop/cbhandles.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/cbhandles.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/dns.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/errors.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/loop.c -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/loop.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/loop.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/os_signal.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/os_signal.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/request.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/request.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/server.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  copying uvloop/server.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
  creating build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/async_.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/async_.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/basetransport.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/basetransport.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/handle.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/handle.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/idle.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/idle.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/pipe.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/pipe.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/poll.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/poll.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/process.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/process.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/signal.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/signal.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/stream.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/stream.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/streamserver.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/streamserver.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/tcp.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/tcp.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/timer.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/timer.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/udp.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  copying uvloop/handles/udp.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
  creating build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
  copying uvloop/includes/__init__.py -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
  copying uvloop/includes/consts.pxi -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
  copying uvloop/includes/python.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
  copying uvloop/includes/stdlib.pxi -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
  copying uvloop/includes/system.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
  copying uvloop/includes/uv.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
  running build_ext
  autogen.sh: line 28: automake: command not found
  autogen.sh: line 33: test: : integer expression expected
  autogen.sh: line 34: test: : integer expression expected
  + glibtoolize --copy
  glibtoolize: putting auxiliary files in '.'.
  glibtoolize: copying file './ltmain.sh'
  glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
  glibtoolize: copying file 'm4/libtool.m4'
  glibtoolize: copying file 'm4/ltoptions.m4'
  glibtoolize: copying file 'm4/ltsugar.m4'
  glibtoolize: copying file 'm4/ltversion.m4'
  glibtoolize: copying file 'm4/lt~obsolete.m4'
  + aclocal -I m4
  autogen.sh: line 44: aclocal: command not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/setup.py", line 74, in <module>
      include_package_data=True
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Volumes/Data/Users/dpadovano/.virtualenvs/tran/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Volumes/Data/Users/dpadovano/.virtualenvs/tran/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
      _build_ext.run(self)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
      self.build_extensions()
    File "/private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/setup.py", line 38, in build_extensions
      self.build_libuv()
    File "/private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/setup.py", line 31, in build_libuv
      check=True)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 711, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['/bin/sh', 'autogen.sh']' returned non-zero exit status 127

  ----------------------------------------
  Failed building wheel for uvloop
  Running setup.py clean for uvloop
Failed to build uvloop
Installing collected packages: uvloop
  Running setup.py install for uvloop ... error
    Complete output from command /Volumes/Data/Users/dpadovano/.virtualenvs/tran/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-76evy8ep-record/install-record.txt --single-version-externally-managed --compile --install-headers /Volumes/Data/Users/dpadovano/.virtualenvs/tran/bin/../include/site/python3.5/uvloop:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.10-x86_64-3.5
    creating build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/__init__.py -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/_testbase.py -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    running egg_info
    writing dependency_links to uvloop.egg-info/dependency_links.txt
    writing uvloop.egg-info/PKG-INFO
    writing top-level names to uvloop.egg-info/top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'uvloop.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'uvloop.egg-info/SOURCES.txt'
    copying uvloop/cbhandles.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/cbhandles.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/dns.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/errors.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/loop.c -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/loop.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/loop.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/os_signal.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/os_signal.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/request.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/request.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/server.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    copying uvloop/server.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop
    creating build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/async_.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/async_.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/basetransport.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/basetransport.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/handle.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/handle.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/idle.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/idle.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/pipe.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/pipe.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/poll.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/poll.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/process.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/process.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/signal.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/signal.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/stream.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/stream.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/streamserver.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/streamserver.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/tcp.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/tcp.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/timer.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/timer.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/udp.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    copying uvloop/handles/udp.pyx -> build/lib.macosx-10.10-x86_64-3.5/uvloop/handles
    creating build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
    copying uvloop/includes/__init__.py -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
    copying uvloop/includes/consts.pxi -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
    copying uvloop/includes/python.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
    copying uvloop/includes/stdlib.pxi -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
    copying uvloop/includes/system.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
    copying uvloop/includes/uv.pxd -> build/lib.macosx-10.10-x86_64-3.5/uvloop/includes
    running build_ext
    autogen.sh: line 28: automake: command not found
    autogen.sh: line 33: test: : integer expression expected
    autogen.sh: line 34: test: : integer expression expected
    + glibtoolize --copy
    + aclocal -I m4
    autogen.sh: line 44: aclocal: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/setup.py", line 74, in <module>
        include_package_data=True
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Volumes/Data/Users/dpadovano/.virtualenvs/tran/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Volumes/Data/Users/dpadovano/.virtualenvs/tran/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/setup.py", line 38, in build_extensions
        self.build_libuv()
      File "/private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/setup.py", line 31, in build_libuv
        check=True)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 711, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['/bin/sh', 'autogen.sh']' returned non-zero exit status 127

    ----------------------------------------
Command "/Volumes/Data/Users/dpadovano/.virtualenvs/tran/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-76evy8ep-record/install-record.txt --single-version-externally-managed --compile --install-headers /Volumes/Data/Users/dpadovano/.virtualenvs/tran/bin/../include/site/python3.5/uvloop" failed with error code 1 in /private/var/folders/lm/p6m9r8350k9c5my6ggm13dvcfkrtj7/T/pip-build-8vb__f85/uvloop/
```

**Comment by digitaldavenyc** [comment]
@1st1 Full output of both methods included if this helps at all

**Comment by dabeaz** [comment]
It's complaining about automake not being installed.   I had to install recent versions of autoconf, automake, and libtool to get uvloop to build. After that, 'pip' installing it worked.

**Comment by 1st1** [comment]
I think I'll simply run autotools on my machine before sdisting.

**Comment by 1st1** [comment]
@digitaldavenyc Please try uvloop 0.4.12

**Comment by digitaldavenyc** [comment]
@dabeaz That did it!

**Comment by digitaldavenyc** [comment]
@1st1 Should the updated uvloop 0.4.12 include the packages?

**Comment by 1st1** [comment]
@digitaldavenyc The updated uvloop doesn't need autotools at all, if you're installing it with pip. Alright, closing the issue.

**Comment by digitaldavenyc** [comment]
Ok thanks. I'm going to try this on a different OSX machine tonight to confirm.

**Comment by 1st1** [comment]
Please re-open the issue if it fails.

**Comment by digitaldavenyc** [comment]
I think you'll have to ... the public is not able to reopen issues on this repo.
