### ISSUE TITLE
UVLoop and AsyncIO

### ISSUE THREAD

**Issue by python-programmer** [MagicStack/uvloop#121]
* **uvloop version**: 0.9.1
* **Python version**: 3.6
* **Platform**: MacOS
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: NO

I run below code (websockets and uvloop):

```python
#!/usr/bin/env python

import asyncio
import datetime
import random
import uvloop
import websockets

async def time(websocket, path):
    while True:
        now = datetime.datetime.utcnow().isoformat() + 'Z'
        await websocket.send(now)
        await asyncio.sleep(random.random() * 3)

start_server = websockets.serve(time, '127.0.0.1', 5678)

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

and got below errors:

```
Traceback (most recent call last):
  File "/Users/ٓٓٓXXX/Documents/Projects/TheProject/main.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(start_server)
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 530, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/XXX/Documents/Projects/real_time_env/lib/python3.6/site-packages/websockets/server.py", line 725, in __await__
    server = yield from self._creating_server
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1013, in create_server
    infos = yield from tasks.gather(*fs, loop=self)
RuntimeError: Task <Task pending coro=<_wrap_awaitable() running at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:530> cb=[run_until_complete.<locals>.<lambda>()]> got Future <_GatheringFuture pending> attached to a different loop

Process finished with exit code 1
```

and also with **autobahn**
what's wrong?

**rabbit** and **turtle** race.

**Comment by 1st1** [comment]
Doesn't look like a uvloop issue. I'd suggest to file this issue to the websockets project.

**Comment by python-programmer** [comment]
```
1. import asyncio
2. import uvloop
3. asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```

Does order matter?

below code works:

```
#!/usr/bin/env python


import datetime
import random
import asyncio # --------------------> this
import uvloop # --------------------> this
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy()) # --------------------> this
import websockets

async def time(websocket, path):
    while True:
        now = datetime.datetime.utcnow().isoformat() + 'Z'
        await websocket.send(now)
        await asyncio.sleep(random.random() * 3)

start_server = websockets.serve(time, '127.0.0.1', 5678)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

why?

**Comment by 1st1** [comment]
Well, to me the backtrace looks like something is working just by accident in asyncio and breaks in uvloop, because it schedules things slightly differently. I can't check it right now myself, we'll take a look later.

**Comment by python-programmer** [comment]
Thank you for your prompt reply.

**Comment by 1st1** [comment]
Closing this one. Feel free to follow up if you think it's a uvloop issue.
