### ISSUE TITLE
uvloop and pypy: error with create_server

### ISSUE THREAD

**Issue by janhn** [MagicStack/uvloop#132]
* **uvloop version**: 0.9.1
* **Python version**: Python 3.5.3 / [PyPy 5.10.1 with GCC 7.2.0]
* **Platform**: linux

Trying uvloop with pypy3, I'm getting the following trace:
```
  File "uvloop_pypy3-4.py", line 20, in test_server
    loop.create_server(protocol, '127.0.0.1', 10321))
  File "/opt/pypy3/lib-python/3/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/opt/pypy3/lib-python/3/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/opt/pypy3/lib-python/3/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/opt/pypy3/lib-python/3/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "uvloop/loop.pyx", line 1521, in create_server
TypeError: 'NoneType' object is not iterable
```

Here's the test case:
```python
import asyncio
import traceback
import logging
import uvloop

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

log = logging.getLogger()
log.setLevel(logging.DEBUG)
log.debug('Event loop is %r', asyncio.get_event_loop())


def protocol():
    return asyncio.Protocol()


async def test_server(loop):
    try:
        ser = await loop.create_task(
            loop.create_server(protocol, '127.0.0.1', 10321))
    except Exception:
        log.warning(traceback.format_exc())
        ser = None

    await asyncio.sleep(0.2)

    assert ser is not None
    print(ser.sockets)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.create_task(test_server(loop))
    try:
        loop.run_forever()
    finally:
        loop.stop()
```

**Comment by 1st1** [comment]
Does it work with CPython?

PyPy isn't officially supported by uvloop, so some things can be broken.  I'd appreciate you investigating this and making a PR if it's a bug.

**Comment by janhn** [comment]
@1st1 Yes, it works with CPython.

I can try, but I'm not familiar with Cython. This is what I'm getting after some digging:
```
Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/handles/timer.pyx", line 80, in uvloop.loop.__uvtimer_callback
KeyError: <TimerHandle _set_result_unless_cancelled created at /opt/pypy3/lib-python/3/asyncio/tasks.py:522>
```

**Comment by extraymond** [comment]
+1 for the problem.

I think the problem might be pypy not supporting async generator syntax since it's still based on 3.5.

**Comment by 1st1** [comment]
I'm going to close this as PyPy compatibility isn't something I'm concerned with. The performance of vanilla asyncio under PyPy should be acceptable, so missing proper uvloop support for PyPy shouldn't be a deal breaker.
