### ISSUE TITLE
Make test has 4 fails on ubuntu 16.04

### ISSUE THREAD

**Issue by MarkReedZ** [MagicStack/uvloop#133]
Ubuntu 16.04 python 3.5.2

make test has 4 fails on a new DO droplet.

Full output
https://gist.github.com/MarkReedZ/1208fcbe4ff117fffac7765cb8a62211
```
======================================================================
ERROR: test_ssl_connect_accepted_socket (test_tcp.Test_AIO_TCPSSL)
 ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ch/uvloop/tests/test_tcp.py", line 1156, in test_ssl_connect_accepted_socket
    self, server_context, client_context)
  File "/home/ch/uvloop/tests/test_tcp.py", line 902, in test_connect_accepted_socket
    loop.connect_accepted_socket(
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'connect_accepted_socket'

 ======================================================================
ERROR: test_create_unix_server_existing_path_sock (test_unix.Test_AIO_Unix)
 ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ch/uvloop/tests/test_unix.py", line 166, in test_create_unix_server_existing_path_sock
    srv = self.loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 264, in create_unix_server
    raise OSError(errno.EADDRINUSE, msg) from None
OSError: [Errno 98] Address '/tmp/tmph6hkfygr/sock' is already in use

 ======================================================================
FAIL: test_cython_coro_is_coroutine (test_cython.TestCythonIntegration)
 ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ch/uvloop/tests/test_cython.py", line 14, in test_cython_coro_is_coroutine
    self.assertEqual(_format_coroutine(coro), '_test_coroutine_1()')
AssertionError: '_test_coroutine_1() done, defined at uvloop/loop.pyx:2834' != '_test_coroutine_1()'
- _test_coroutine_1() done, defined at uvloop/loop.pyx:2834
+ _test_coroutine_1()


 ======================================================================
FAIL: test_socket_cancel_sock_sendall (test_sockets.TestUVSockets)
 ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ch/uvloop/uvloop/_testbase.py", line 98, in tearDown
    self.fail('unexpected calls to loop.call_exception_handler()')
AssertionError: unexpected calls to loop.call_exception_handler()

----------------------------------------------------------------------
```
Fresh ubuntu 16.04:

sudo apt-get install libtool
sudo apt-get install automake
git clone --recursive https://github.com/MagicStack/uvloop.git
cd uvloop 
python3 -m venv myvenv 
source myvenv/bin/activate
pip install Cython 
make
make test

**Comment by 1st1** [comment]
Please try the latest master branch.

**Comment by 1st1** [comment]
This one seems to be very outdated now, closing it. Thanks for submitting a bug report anyways!
