### ISSUE TITLE
windows support?

### ISSUE THREAD

**Issue by sunwangme** [MagicStack/uvloop#14]
wonderful project！when to suppert windows?

**Comment by 1st1** [comment]
When we find a volunteer to implement it ;)

**Comment by brickgao** [comment]
@1st1 Hi, I'm interested in implementing this proposal, is anyone already working on it ;)?

**Comment by 1st1** [comment]
@brickgao As far as I know no one is.

**Comment by brickgao** [comment]
@1st1 I have a little trouble porting `posix.signal` to Windows in https://github.com/MagicStack/uvloop/blob/master/uvloop/os_signal.pyx#L1 . I could not find a good way to implement it because of the difference in signal between Windows and *nix. Could you please give me some advice?

**Comment by 1st1** [comment]
I don't think Windows support signals, so you should probably add checks like `if not __WINDOWS__` around code that touches `loop.py_signals` and `loop.uv_signals`.

**Comment by 1st1** [comment]
@brickgao Do you think we should find more people to look into this problem?

**Comment by brickgao** [comment]
@1st1 Sure, I find that there isn't a quick way to port uvloop with the native Windows API. I would try to port uvloop with Cygwin these days first, cuz I find Cygwin provide most of the *NIX API on Windows.

**Comment by brickgao** [comment]
@1st1 I find that Cygwin haven't provided Python3.5 officially :(, so we should work on it with the native Windows API again. Maybe we should find more people to look into this problem.

There are two major parts we need to port, socket and signal.

For socket, most of socket functions could be easy to ported by changing the header file, but Windows don't provide `socketpair`. Referring to https://github.com/ncm/selectable-socketpair and https://github.com/python/cpython/blob/c6ae2fcc724cbebb14e7c434b89eabdd64802cb3/Lib/asyncio/windows_utils.py#L37, it's possible to implement a `socketpair` that support AF_INET and AF_INET6, but it doesn't support AF_UNIX.
For signal, Windows provides a function `signal` to change the handlers of specific signal, but it doesn't provide the function to get the current handler of specific signal and it also doesn't provide `sigfillset`.

**Comment by schlamar** [comment]
Libuv already provides a platform agnostic interface to signals and sockets (e.g. http://docs.libuv.org/en/v1.x/signal.html). You shouldn't have to deal with the Windows API at all.

**Comment by 1st1** [comment]
@schlamar You should have looked at uvloop source code first, before assuming that we don't know some basic libuv APIs.

@brickgao Sorry for the delayed reply. For signals specifically I use `sigaction` to make sure that: 

1. uvloop restores CPython's signal handlers
2. `Ctrl+C` is handled correctly, i.e. `PyErr_SetInterrupt` is called when uvloop runs Python callbacks.

For the Windows port we don't need (1). We might need to play with Windows APIs to workaround (2), I suggest you to look at how CPython handles Ctrl+C on Windows.

As for `socketpair`–the whole subprocess handling code is complicated. I had to copy the logic from `subprocess.py` (and its C-level helper) to make uvloop's subprocess behave exactly like CPython's. Good news is that we can learn how `subprocess.py` uses Windows APIs, and copy that approach to uvloop.

**Comment by iceb0y** [comment]
Had a quick hack to make it buildable in windows (win7, python 3.5.2 x64): https://github.com/iceb0y/uvloop/commit/fa2b7db1d7940149bb8d16e856e7d1a642f3e6b8

build snippet:
in /vendor/libuv, *use python2*
```
vcbuild.bat x64 release
```
in /, use python3, do the same as makefile
```
cython -3 -a -p uvloop/loop.pyx
python setup.py build_ext --inplace
```

Had a test with aiohttp server - the current stucking problem is that uvloop uses `os_dup` in [multiple places](https://github.com/MagicStack/uvloop/search?q=os_dup) to duplicate `UVSocketHandle._fileno`, where `os_dup = os.dup` and it duplicates posix file handles. In windows, posix file handle is implemented as an additional layer on NT handles where the handle numbers are not equal.

Notice that `os_dup` is also used to duplicate posix handle in `uvloop/loop.pyx` and `uvloop/handles/process.pyx`. So we need to differentiate between this two kinds of dups.

**Comment by iceb0y** [comment]
dup is introduced in 6e9c43bdecfad711c38c423fbada8fd8b86ddf7f

maybe we need to find another way to solve the problem described by the commit?

**Comment by 1st1** [comment]
Your PR looks very good, thanks a lot for working on this. I believe we don't need to do anything special for signals or forks. As for `dup`, I'll fix a bug in asyncio and change how uvloop implements `get_extra_info` in a couple of weeks.

**Comment by iceb0y** [comment]
I suggest to make some Socket extending `socket.socket` like:

```
cdef class Socket(socket.socket):
    cdef UVSocketHandle handle
```

**Comment by brickgao** [comment]
Some workarounds to the signal based on @iceb0y 's commits: https://github.com/brickgao/uvloop/commit/eb9b9b7881fb1950e61033c3ba3934daf0a0c7e0

**Comment by 1st1** [comment]
> What do you plan for dup?

Just to remove it completely. Right now it's there to save uvloop from segfaulting when someone uses sockets from transports with add_writer API.

**Comment by asvetlov** [comment]
@1st1 I've fixed sendfile support on aiohttp master.
Funny fact: on travis dupped socket was in blocking mode.
Honestly I've not dug into but had added just socket.setblocking(False) call.

**Comment by 1st1** [comment]
> @1st1 I've fixed sendfile support on aiohttp master.

Super cool! Thanks!

> Funny fact: on travis dupped socket was in blocking mode.

Wow. Maybe this is something worth investigating? Is it something that asyncio causes?

**Comment by iceb0y** [comment]
> Some workarounds to the signal based on @iceb0y 's commits: brickgao@eb9b9b7

@1st1 I think the windows signal code is actually platform-independent
1. Is it correct?
2. Should we just use it for all platforms for simplification?

**Comment by asvetlov** [comment]
>> Funny fact: on travis dupped socket was in blocking mode.
> Wow. Maybe this is something worth investigating? Is it something that asyncio causes?

@1st1 I cannot reproduce the problem locally. The only error what I have is travis report: https://travis-ci.org/KeepSafe/aiohttp/builds/157838616
Something like this:
```
    resp = yield from sender().send(request, filepath)
  File "/opt/python/3.5.0/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/travis/build/KeepSafe/aiohttp/aiohttp/file_sender.py", line 148, in send
    yield from self._sendfile(request, resp, f, file_size)
  File "/opt/python/3.5.0/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/travis/build/KeepSafe/aiohttp/aiohttp/file_sender.py", line 86, in _sendfile_system
    ''.join(headers).encode('utf-8'))
  File "uvloop/loop.pyx", line 1831, in sock_sendall (uvloop/loop.c:29654)
ValueError: the socket must be non-blocking
```
`sock.setblocking(False)` has solved the problem.
I have no Idea why it works with some configurations but fails with others.

**Comment by 1st1** [comment]
@iceb0y In the latest version of uvloop I've redesigned how signals are implemented. No more libuv or system API calls, I now only use Python's `signal` module. This should help with the Windows port.

**Comment by iceb0y** [comment]
tested on windows - the signal handling code doesn't work on windows, probably due to usage of `socketpair`.

`Loop._setup_signals` -> `Loop._add_reader` -> `UVPoll.new` -> `UVPoll._init` -> `uv.uv_poll_init` -> `OSError: [Errno 4050] Unknown error`.

Why does signal handling use a `socketpair` which seems to post notification to the loop?

**Comment by 1st1** [comment]
FWIW I'm working on to add Windows support in https://github.com/MagicStack/uvloop/tree/win. Any help is welcome.

**Comment by 1st1** [comment]
Here's the PR https://github.com/MagicStack/uvloop/pull/62

**Comment by martmists** [comment]
For those on windows 10, I believe you can use bash on ubuntu and install uvloop on there, or at least that seems to have worked for me.

**Comment by 1st1** [comment]
> For those on windows 10, I believe you can use bash on ubuntu and install uvloop on there for now, or at least that seems to have worked for me.

Great! FWIW I don't have time to focus on the IOCP win port right now, but I can definitely help with reviews/suggestions if someone is interested in it.

**Comment by bfbd888** [comment]
Is it support "Bash on Ubuntu on Windows"?

It's running on Windows Subsystem for Linux（WSL）。

**Comment by 1st1** [comment]
@bfbd888 I think it should work, but I haven't tried it myself.

**Comment by fyears** [comment]
A side note on 2017/02/16 for those who are interested later.

I come across these issues today (actually I want to install [`sanic`](https://github.com/channelcat/sanic)), and try the latest windows branch commit https://github.com/MagicStack/uvloop/commit/3c741b4c27fec94569ff8c65222e4f314cf44079.

I `git clone` the repo and try to `python setup.py install`. I meet an error complaining python 2.7 not found because of https://github.com/MagicStack/uvloop/blob/win/setup.py#L227. (It's ironical because `uvloop` is designed for Python 3.5 +.) Python 2.7 is required for `gyp`, so I installed Python 2.7 and manually change that line to hard code my Python 2.7 path.

After that, I could successfully build and import `uvloop`! And the hello world of `sanic` works, too.

I also run the [`tests/`](https://github.com/MagicStack/uvloop/tree/win/tests). These tests failed:

```text
test_dns.py
test_sockets.py
test_tcp.py
test_udp.py
```

**Comment by hexcola** [comment]
@bfbd888 @1st1 it works on "Bash on Ubuntu on Windows", tested on Windows 10.

![Sanic on windows 10 using uvloop](https://raw.githubusercontent.com/hexcola/Notebook/master/Sanic/_images/Image%20052.png)

**Comment by tritium21** [comment]
Bash on Windows is Windows Subsystem for Linux.  You are not running a windows executable, you are quite literally running (at the time of your post) Ubuntu 14.04 x86-64.  WSL is not a production tool, it exists to let windows based developers write binaries that will be deployed on real ubuntu 14.04 (and now 16.04) machines.

WSL runs real linux binaries on the windows kernel ... unreliably.  It's not a real solution to running on windows.

**Comment by matpow2** [comment]
What is the status on this?

**Comment by 1st1** [comment]
@matpow2 libuv has some design inconsistencies between Posix/Win versions. For nodejs they don't matter, but for uvloop they need to be fixed first. Unfortunately, that's a considerable chunk of work, and I don't need uvloop to be compatible with Windows for my own use. Therefore, the work on the port is stalled.

If someone wants to champion the PR, I'll certainly help them (both with changes to uvloop and to libuv).

**Comment by luckcolors** [comment]
@1st1 Hey, i've noticed that the in the PR you refer to an uvloop pr wich has been merged. https://github.com/libuv/libuv/pull/1447
Could you check if working on this issue can proceed? :)

**Comment by floqqi** [comment]
@1st1 @luckcolors would be interesting for me, too! Any chance? Would be great to see frameworks like Sanic working on Windows :)

**Comment by 1st1** [comment]
> Would be great to see frameworks like Sanic working on Windows :)

Nothing prevents sanic to work on Windows.  uvloop should be an *optional* dependency.

**Comment by aknaebel** [comment]
Some project like uvicorn (https://github.com/encode/uvicorn) use uvloop and cannot be used on windows which is very restrictive

**Comment by 1st1** [comment]
uvloop should be an **optional** dependency.  It doesn't provide any extra APIs on top of vanilla asyncio, it's an accelerator.  It happens that uvloop only works on posix right now and it's OK.

Please file a bug report to uvicorn to make uvloop dep optional.

**Comment by dakyri** [comment]
Yuri, what's the state of play with getting the windows port  working? I might be interested getting this done (I have a use case for it) ... at least as one contributor. I've worked with libuv in c/c++, so I know my way around that. Any idea how much work would be invoved time wise to get something functional?

**Comment by 1st1** [comment]
I almost got it working, except cases where the API accepts an existing socket to work with.  I.e. `create_server(sock=sock)`, not `create_server(addr)`.  The best approach would be to build uvloop on Windows with the patch (https://github.com/MagicStack/uvloop/pull/62) applied and work from that point.

**Comment by dakyri** [comment]
Cool! That sounds like it's viable or close enough for me as it stands already, but I'll be happy to pick up the ball and contribute moving forwards.

**Comment by matemax** [comment]
@1st1 ,can you merge master into win branch?

**Comment by 1st1** [comment]
I'll take a look on Monday. Are you using the win branch?

**Comment by matemax** [comment]
No, but our project is using uvloop and python 3.6. I am going to make it cross-platform. 25.11.2017, 17:19, "Yury Selivanov" <notifications@github.com>:I'll take a look on Monday. Are you using the win branch?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by 1st1** [comment]
I've rebased it.  Have no idea if it still compiles on Windows, but it does compile OK on *nix after the rebase.

**Comment by matemax** [comment]
<details>
 <summary>Failed build</summary>
 warning: uvloop\handles/stream.pyx:318:8: Unreachable code
    warning: uvloop\loop.pyx:2750:4: Unreachable code

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                self._fatal_error(exc, True)
                return

            cdef:
                int backend_id
                system.epoll_event dummy_event
               ^
    ------------------------------------------------------------

    uvloop\handles/poll.pyx:67:12: 'epoll_event' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

            cdef:
                int backend_id
                system.epoll_event dummy_event

            if system.PLATFORM_IS_LINUX:
                    ^
    ------------------------------------------------------------

    uvloop\handles/poll.pyx:69:17: cimported module has no attribute 'PLATFORM_IS_LINUX'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                # after calling uv_poll_stop.

                backend_id = uv.uv_backend_fd(self._loop.uvloop)
                if backend_id != -1:
                    memset(&dummy_event, 0, sizeof(dummy_event))
                    system.epoll_ctl(
                         ^
    ------------------------------------------------------------

    uvloop\handles/poll.pyx:82:22: cimported module has no attribute 'epoll_ctl'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                backend_id = uv.uv_backend_fd(self._loop.uvloop)
                if backend_id != -1:
                    memset(&dummy_event, 0, sizeof(dummy_event))
                    system.epoll_ctl(
                        backend_id,
                        system.EPOLL_CTL_DEL,
                             ^
    ------------------------------------------------------------

    uvloop\handles/poll.pyx:84:26: cimported module has no attribute 'EPOLL_CTL_DEL'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                        with open(self._errpipe_write, 'wb') as f:
                            f.write(str(ex.__class__.__name__).encode())
                            f.write(b':')
                            f.write(str(ex.args[0]).encode())
                    finally:
                        system._exit(255)
                             ^
    ------------------------------------------------------------

    uvloop\handles/process.pyx:173:26: cimported module has no attribute '_exit'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                        with open(self._errpipe_write, 'wb') as f:
                            f.write(str(ex.__class__.__name__).encode())
                            f.write(b':')
                            f.write(str(ex.args[0]).encode())
                    finally:
                        system._exit(255)
                             ^
    ------------------------------------------------------------

    uvloop\handles/process.pyx:173:26: cimported module has no attribute '_exit'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef __socketpair():
        cdef:
            int fds[2]
            int err

        err = system.socketpair(uv.AF_UNIX, uv.SOCK_STREAM, 0, fds)
                   ^
    ------------------------------------------------------------

    uvloop\handles/process.pyx:719:16: cimported module has no attribute 'socketpair'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Maxim\AppData\Local\Temp\pip-joj6i769-build\setup.py", line 370, in <module>
        test_suite='tests.suite'
      File "c:\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python36\lib\site-packages\setuptools\command\egg_info.py", line 279, in run
        self.find_sources()
      File "c:\python36\lib\site-packages\setuptools\command\egg_info.py", line 306, in find_sources
        mm.run()
      File "c:\python36\lib\site-packages\setuptools\command\egg_info.py", line 533, in run
        self.add_defaults()
      File "c:\python36\lib\site-packages\setuptools\command\egg_info.py", line 562, in add_defaults
        sdist.add_defaults(self)
      File "c:\python36\lib\site-packages\setuptools\command\py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "c:\python36\lib\site-packages\setuptools\command\py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "c:\python36\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "c:\python36\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "C:\Users\Maxim\AppData\Local\Temp\pip-joj6i769-build\setup.py", line 138, in finalize_options
        annotate=self.cython_annotate)
      File "c:\python36\lib\site-packages\Cython\Build\Dependencies.py", line 1039, in cythonize
        cythonize_one(*args)
      File "c:\python36\lib\site-packages\Cython\Build\Dependencies.py", line 1161, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: uvloop/loop.pyx
    uvloop/loop.pyx: cannot find cimported module '.includes'
    uvloop/loop.pxd: cannot find cimported module '.includes'
    Compiling uvloop/loop.pyx because it changed.
    [1/1] Cythonizing uvloop/loop.pyx

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Maxim\AppData\Local\Temp\pip-joj6i769-build\

g:\python_script\facestreammanager2>pip install https://github.com/MagicStack/uvloop/archive/win.zip
Collecting https://github.com/MagicStack/uvloop/archive/win.zip
  Downloading https://github.com/MagicStack/uvloop/archive/win.zip (168kB)
    100% |████████████████████████████████| 174kB 356kB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\uvloop.egg-info
    writing pip-egg-info\uvloop.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\uvloop.egg-info\dependency_links.txt
    writing top-level names to pip-egg-info\uvloop.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\uvloop.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    warning: uvloop\handles/stream.pyx:318:8: Unreachable code
    warning: uvloop\loop.pyx:2750:4: Unreachable code

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                self._fatal_error(exc, True)
                return

            cdef:
                int backend_id
                system.epoll_event dummy_event
               ^
    ------------------------------------------------------------

    uvloop\handles/poll.pyx:67:12: 'epoll_event' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

            cdef:
                int backend_id
                system.epoll_event dummy_event

            if system.PLATFORM_IS_LINUX:
                    ^
    ------------------------------------------------------------

    uvloop\handles/poll.pyx:69:17: cimported module has no attribute 'PLATFORM_IS_LINUX'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                # after calling uv_poll_stop.

                backend_id = uv.uv_backend_fd(self._loop.uvloop)
                if backend_id != -1:
                    memset(&dummy_event, 0, sizeof(dummy_event))
                    system.epoll_ctl(
                         ^
    ------------------------------------------------------------

    uvloop\handles/poll.pyx:82:22: cimported module has no attribute 'epoll_ctl'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                backend_id = uv.uv_backend_fd(self._loop.uvloop)
                if backend_id != -1:
                    memset(&dummy_event, 0, sizeof(dummy_event))
                    system.epoll_ctl(
                        backend_id,
                        system.EPOLL_CTL_DEL,
                             ^
    ------------------------------------------------------------

    uvloop\handles/poll.pyx:84:26: cimported module has no attribute 'EPOLL_CTL_DEL'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                        with open(self._errpipe_write, 'wb') as f:
                            f.write(str(ex.__class__.__name__).encode())
                            f.write(b':')
                            f.write(str(ex.args[0]).encode())
                    finally:
                        system._exit(255)
                             ^
    ------------------------------------------------------------

    uvloop\handles/process.pyx:173:26: cimported module has no attribute '_exit'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                        with open(self._errpipe_write, 'wb') as f:
                            f.write(str(ex.__class__.__name__).encode())
                            f.write(b':')
                            f.write(str(ex.args[0]).encode())
                    finally:
                        system._exit(255)
                             ^
    ------------------------------------------------------------

    uvloop\handles/process.pyx:173:26: cimported module has no attribute '_exit'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef __socketpair():
        cdef:
            int fds[2]
            int err

        err = system.socketpair(uv.AF_UNIX, uv.SOCK_STREAM, 0, fds)
                   ^
    ------------------------------------------------------------

    uvloop\handles/process.pyx:719:16: cimported module has no attribute 'socketpair'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Maxim\AppData\Local\Temp\pip-dgf_dtfv-build\setup.py", line 370, in <module>
        test_suite='tests.suite'
      File "c:\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python36\lib\site-packages\setuptools\command\egg_info.py", line 279, in run
        self.find_sources()
      File "c:\python36\lib\site-packages\setuptools\command\egg_info.py", line 306, in find_sources
        mm.run()
      File "c:\python36\lib\site-packages\setuptools\command\egg_info.py", line 533, in run
        self.add_defaults()
      File "c:\python36\lib\site-packages\setuptools\command\egg_info.py", line 562, in add_defaults
        sdist.add_defaults(self)
      File "c:\python36\lib\site-packages\setuptools\command\py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "c:\python36\lib\site-packages\setuptools\command\py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "c:\python36\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "c:\python36\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "C:\Users\Maxim\AppData\Local\Temp\pip-dgf_dtfv-build\setup.py", line 138, in finalize_options
        annotate=self.cython_annotate)
      File "c:\python36\lib\site-packages\Cython\Build\Dependencies.py", line 1039, in cythonize
        cythonize_one(*args)
      File "c:\python36\lib\site-packages\Cython\Build\Dependencies.py", line 1161, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: uvloop/loop.pyx
    uvloop/loop.pyx: cannot find cimported module '.includes'
    uvloop/loop.pxd: cannot find cimported module '.includes'
    Compiling uvloop/loop.pyx because it changed.
    [1/1] Cythonizing uvloop/loop.pyx
</details>

**Comment by nsavelyeva** [comment]
Hi All,
I'm looking forward to this feature, too. Respect and many thanks to all devs involved.
I tried today 'pip install uvloop' on Windows 10 and it failed with RuntimeError: uvloop does not support Windows at the moment.

**Comment by AymanEG** [comment]
Hello from 2018 , good luck guys completing it :)

**Comment by griimnak** [comment]
Goodluck, windows support would still be appreciated

**Comment by ofek** [comment]
Any progress?

**Comment by tweakimp** [comment]
It would be helpful if it at least said in the readme that it currently has no Windows support.

**Comment by ma5oud180** [comment]
Hi Yuri, I understand that you are super busy, but I myself & as I see lots of people, are not able and have not the skills to make it work on Windows. I would like to kindly ask you to finally, easily make it possible to install this package on Windows 64 bit systems. Lots of people are looking for it. Many thanks

**Comment by jmclemo6** [comment]
Any updates on this? If I could be caught up to speed on what's been done and discovered, I think I could start working on it.

**Comment by ofek** [comment]
I'd love to help test!

**Comment by 1st1** [comment]
> Any updates on this? If I could be caught up to speed on what's been done and discovered, I think I could start working on it.

Sure, by all means. I'd start with trying to recover the `win` branch. Please open new issues as you progress through this.

**Comment by 1st1** [comment]
### I'm locking this issue. I don't have time to work on this in personal time. It doesn't make sense to work on this during my work time. If the community _really_ needs this then someone will start submitting PRs which I'll happily review and help with advice.
