### ISSUE TITLE
UVloop installation issue

### ISSUE THREAD

**Issue by jeffiy** [MagicStack/uvloop#193]
* **uvloop version 0.11**:
* **Python version 3.6**:
* **Platform ubuntu 16.05 LTS Xenail on arm processor pynq board**:

RuntimeError: the libuv submodule has not been checked out; try running "git submodule init; git submodule update"
 I am getting this error how to resolve this issue i have installed libuv version 1.4.2

**Comment by 1st1** [comment]
Did you try running "git submodule init; git submodule update"?

**Comment by jeffiy** [comment]
no i a manually adding libuv files in vendor folder in repository before installing.

**Comment by jeffiy** [comment]
Actually i am having proxy issues therefore it command didn't work for me.

**Comment by 1st1** [comment]
> no i a manually adding libuv files in vendor folder in repository before installing.

Well, you're on your own then, I can't help you here :(

**Comment by jeffiy** [comment]
Sorry for bearing me just one question will UVloop work on arm processor.

**Comment by 1st1** [comment]
Closing this one, please feel free to reopen!

**Comment by jeffiy** [comment]
@1st1  **now i am installing it via pip and getting this error**

    make: Warning: File 'm4/libtool.m4' has modification time 1106448 s in the f                                                                             uture
    CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /tmp/pip-install-q2hsbafe/uv                                                                             loop/build/libuv/missing aclocal-1.14 -I m4
    /tmp/pip-install-q2hsbafe/uvloop/build/libuv/missing: line 81: aclocal-1.14:                                                                              command not found
    WARNING: 'aclocal-1.14' is missing on your system.
             You should only need it if you modified 'acinclude.m4' or
             'configure.ac' or m4 files included by 'configure.ac'.
             The 'aclocal' program is part of the GNU Automake package:
             <http://www.gnu.org/software/automake>
             It also requires GNU Autoconf, GNU m4 and Perl in order to run:
             <http://www.gnu.org/software/autoconf>
             <http://www.gnu.org/software/m4/>
             <http://www.perl.org/>
    Makefile:1116: recipe for target 'aclocal.m4' failed
    make: *** [aclocal.m4] Error 127
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q2hsbafe/uvloop/setup.py", line 270, in <module>
        test_suite='tests.suite'
      File "/opt/python3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 955, in run_co                                                                             mmands
        self.run_command(cmd)
      File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_co                                                                             mmand
        cmd_obj.run()
      File "/opt/python3.6/lib/python3.6/site-packages/setuptools/command/instal                                                                             l.py", line 61, in run
        return orig.install.run(self)
      File "/opt/python3.6/lib/python3.6/distutils/command/install.py", line 545                                                                             , in run
        self.run_command('build')
      File "/opt/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_com                                                                             mand
        self.distribution.run_command(command)
      File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_co                                                                             mmand
        cmd_obj.run()
      File "/opt/python3.6/lib/python3.6/distutils/command/build.py", line 135,                                                                              in run
        self.run_command(cmd_name)
      File "/opt/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_com                                                                             mand
        self.distribution.run_command(command)
      File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_co                                                                             mmand
        cmd_obj.run()
      File "/opt/python3.6/lib/python3.6/site-packages/setuptools/command/build_                                                                             ext.py", line 75, in run
        _build_ext.run(self)
      File "/opt/python3.6/lib/python3.6/site-packages/Cython-0.28.5-py3.6-linux                                                                             -armv7l.egg/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/opt/python3.6/lib/python3.6/distutils/command/build_ext.py", line 3                                                                             39, in run
        self.build_extensions()
      File "/tmp/pip-install-q2hsbafe/uvloop/setup.py", line 198, in build_exten                                                                             sions
        self.build_libuv()
      File "/tmp/pip-install-q2hsbafe/uvloop/setup.py", line 185, in build_libuv
        cwd=LIBUV_BUILD_DIR, env=env, check=True)
      File "/opt/python3.6/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', '-j2', 'CFLAGS= -O2 -fPIC '                                                                             ]' returned non-zero exit status 2.

    ----------------------------------------
  Rolling back uninstall of uvloop
Command "/opt/python3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file_                                                                             _='/tmp/pip-install-q2hsbafe/uvloop/setup.py';f=getattr(tokenize, 'open', open)(                                                                             __file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __fil                                                                             e__, 'exec'))" install --record /tmp/pip-record-6wxxdncc/install-record.txt --si                                                                             ngle-version-externally-managed --compile" failed with error code 1 in /tmp/pip-                                                                             install-q2hsbafe/uvloop/
