### ISSUE TITLE
ssl.SSLError

### ISSUE THREAD

**Issue by Forevka69** [MagicStack/uvloop#208]
* **uvloop version**: uvloop 0.11.3
* **Python version**: 3.7
* **Platform**: ubuntu 18.04
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: cant

Hello, i use uvloop with webhooks in aiogram and sometimes uvloop get this error
with standart loop from asyncio i dont have this error. How can i fix it?

I use this command for generate self-signed certificate:
openssl req -newkey rsa:2048 -sha256 -nodes -keyout PRIVATE.key -x509 -days 365 -out PUBLIC.pem -subj "/C=NG/ST=Lagos/L=Lagos/O=YOUR_NAME_OR_COMPANY_NAME/CN=SERVER_NAME_OR_IP"

12/03/2018 03:41:15 AM ERROR SSL error errno:1 reason: WRONG_SSL_VERSION
protocol: <uvloop.loop.SSLProtocol object at 0x7fd270191b70>
transport: <TCPTransport closed=False reading=False 0x12b3d28>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1051)
12/03/2018 03:41:25 AM ERROR SSL handshake failed
protocol: <uvloop.loop.SSLProtocol object at 0x7fd270199e10>
transport: <TCPTransport closed=False reading=False 0x12b3d28>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 609, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1051)
12/03/2018 03:41:25 AM ERROR SSL error errno:1 reason: NO_SHARED_CIPHER
protocol: <uvloop.loop.SSLProtocol object at 0x7fd270199e10>
transport: <TCPTransport closed=False reading=False 0x12b3d28>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1051)

**Comment by 1st1** [comment]
Hm, could you please try uvloop 0.12.0rc1?

**Comment by Forevka69** [comment]
> Hm, could you please try uvloop 0.12.0rc1?

Ok, i will

**Comment by jlaine** [comment]
@Forevka69 did 0.12.0rc1 solve your issue?

**Comment by 1st1** [comment]
I'm gonna close this one, as the SSL implementation has been rewritten from scratch in 0.12. Please feel free to re-open this issue if the problem appears in 0.12.
