### ISSUE TITLE
uvloop does not support Windows at the moment

### ISSUE THREAD

**Issue by alexandreraufast** [MagicStack/uvloop#326]
ERROR when running pip. It is written nowhere in readme that windows isn't supported.
```pip3 install uvloop
Collecting uvloop
  Downloading uvloop-0.14.0.tar.gz (2.0 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xxx\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TENSOR~1\\AppData\\Local\\Temp\\pip-install-7kabq3oo\\uvloop\\setup.py'"'"'; __file__='"'"'C:\\Users\\TENSOR~1\\AppData\\Local\\Temp\\pip-install-7kabq3oo\\uvloop\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\TENSOR~1\AppData\Local\Temp\pip-install-7kabq3oo\uvloop\pip-egg-info'
         cwd: C:\Users\TENSOR~1\AppData\Local\Temp\pip-install-7kabq3oo\uvloop\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\TENSOR~1\AppData\Local\Temp\pip-install-7kabq3oo\uvloop\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by thePublicer** [comment]
Use Linux  under the VM for example Ubuntu
