### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by gabrielcalderon** [MagicStack/uvloop#365]
Now that Python 3.9 has been officially been release. Is support for Python 3.9 in the near timeline?

Changes: https://docs.python.org/3.9/whatsnew/3.9.html

**Comment by greatvovan** [comment]
Version 0.14.0 throws `NotImplementedError` in the very end of the program, after successful execution:
```
Traceback (most recent call last):
  File "/Users/vryabtsev/PycharmProjects/fastapi/benchmark2.py", line 43, in <module>
    asyncio.run(main())
  File "/Users/vryabtsev/.pyenv/versions/3.9.0/lib/python3.9/asyncio/runners.py", line 49, in run
    loop.run_until_complete(loop.shutdown_default_executor())
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/vryabtsev/.pyenv/versions/3.9.0/lib/python3.9/asyncio/events.py", line 253, in shutdown_default_executor
    raise NotImplementedError
NotImplementedError

Process finished with exit code 1
```
Somehow `AbstractEventLoop.shutdown_default_executor` gets called here, which causes the exception.

**Comment by sileht** [comment]
It's fixed here I guess, https://github.com/MagicStack/uvloop/pull/353.

**Comment by mhxie** [comment]
I have the same issue here. And the benchmark shows that using the Python 3.9 echo server with uvloop 0.14.0 is performing even worse than the default asyncio server. Any idea on this?

**Comment by TheBuky** [comment]
Python 3.9.1 and uvloop 0.14.0 (in django context):

**/usr/lib/python3.9/asyncio/runners.py**, line 49, in **run**:
```
    loop.run_until_complete(loop.shutdown_default_executor())
```
**uvloop/loop.pyx**, line 1456, in **uvloop.loop.Loop.run_until_complete**:
```python
    <source code not available>
```
**/usr/lib/python3.9/asyncio/events.py**, line 253, in **shutdown_default_executor**:
```python
    raise NotImplementedError
````
The problem is always present.

**Comment by Tinche** [comment]
Also, can we get 3.9 wheels up on PyPI? 😇

**Comment by gabrielcalderon** [comment]
Any news on this?

**Comment by fantix** [comment]
Yes - this is on my priority list and I'm hoping to help in getting a release for 3.9 soon!

**Comment by adamantike** [comment]
@fantix, with `0.15.0` release notes mentioning Python 3.9 fixes, and `0.16.0` release notes mentioning Python 3.10 support, should this issue be considered fixed?

With the following simple Dockerfile, I no longer get the `NotImplementedError` exception on version `0.15.0` onwards:

```dockerfile
FROM python:3.9

RUN pip install --no-cache-dir uvloop==0.15.0

RUN echo "\
import asyncio\n\
import uvloop\n\
\n\
async def main():\n\
    ...\n\
\n\
uvloop.install()\n\
asyncio.run(main())\n\
" > /main.py

CMD ["python", "/main.py"]
```

**Comment by fantix** [comment]
Oh yes, thanks for the reminder! Closing now.
