### ISSUE TITLE
yank version 0.15.0 and version 0.15.1 from pypi.org

### ISSUE THREAD

**Issue by graingert** [MagicStack/uvloop#411]
currently when installing uvloop (without pins) pip on py3.6 will download 0.15.1 and then fail. Setting requires_python means pip can pick a different version to install

0.15.0 and 0.15.1 will need to be yanked to avoid issues like encode/uvicorn#953

@1st1 @fantix

**Comment by graingert** [comment]
@asvetlov

**Comment by 1st1** [comment]
Yeah, I'm OK with adding `requires_python` for future releases (a PR would be welcome), but I'm -1 on yanking old releases. First, python 3.6 is pretty old (we'll have 3.10 soon!), second unpinned dependencies are a bad practice anyways. Lastly, yanking the release will break the installation for those people who did pin the package, and I suspect it's a larger group of people.

**Comment by graingert** [comment]
> Lastly, yanking the release will break the installation for those people who did pin the package, and I suspect it's a larger group of people.

No it won't that's the point of a yank

**Comment by 1st1** [comment]
Yeah, it was just pointed out to me what yanking means now for the python packages (https://blog.piwheels.org/new-features-deletion-yanking-and-more/). What a weird non-obvious name. In any case, I withdraw my earlier comment; it does seem that we can yank the older release and fix `requires_python`

**Comment by graingert** [comment]
Thanks requires_python is already set correctly in 0.15.2

**Comment by 1st1** [comment]
Alright, I've just yanked both 0.15.0 and 0.15.1

**Comment by graingert** [comment]
Awesome thanks so much!

**Comment by graingert** [comment]
hooray this "just works" now!

```sh
$ pip install uvloop
Collecting uvloop
  Using cached uvloop-0.14.0-cp36-cp36m-manylinux2010_x86_64.whl (3.9 MB)
Installing collected packages: uvloop
Successfully installed uvloop-0.14.0
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
```

**Comment by graingert** [comment]
overriding the yank with a `==` directive works as expected:

```sh
$ pip install uvloop==0.15.1
Collecting uvloop==0.15.1
  Using cached uvloop-0.15.1.tar.gz (2.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/graingert/.virtualenvs/pip-compile36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n4bxhgfd/uvloop_5552febeed404244bc97225e003a3f16/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n4bxhgfd/uvloop_5552febeed404244bc97225e003a3f16/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kgxhhfdf
         cwd: /tmp/pip-install-n4bxhgfd/uvloop_5552febeed404244bc97225e003a3f16/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n4bxhgfd/uvloop_5552febeed404244bc97225e003a3f16/setup.py", line 5, in <module>
        raise RuntimeError('uvloop requires Python 3.7 or greater')
    RuntimeError: uvloop requires Python 3.7 or greater
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/94/98/9dc814f391b2293ecc790b9752e005296c69c3694fd9975b6cb77c448135/uvloop-0.15.1.tar.gz#sha256=7846828112bfb49abc5fdfc47d0e4dfd7402115c9fde3c14c31818cfbeeb63dc (from https://pypi.org/simple/uvloop/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement uvloop==0.15.1 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31, 0.4.32, 0.4.33, 0.4.34, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0rc1, 0.12.0, 0.12.1, 0.12.2, 0.13.0rc1, 0.13.0, 0.14.0rc1, 0.14.0rc2, 0.14.0, 0.15.0, 0.15.1)
ERROR: No matching distribution found for uvloop==0.15.1
```

same on 3.7, and you get a warning:

```
pip install uvloop==0.15.1         
Collecting uvloop==0.15.1
  Downloading uvloop-0.15.1-cp37-cp37m-manylinux2010_x86_64.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 987 kB/s 
WARNING: The candidate selected for download or install is a yanked version: 'uvloop' candidate (version 0.15.1 at https://files.pythonhosted.org/packages/4c/cc/4703d9b6ca16c689e364aee51ef5dd45f907614f568f7d490d7ef9646ba1/uvloop-0.15.1-cp37-cp37m-manylinux2010_x86_64.whl#sha256=e178c255622d928d464187e3ceba94db88465f6b17909c651483fb73af8d8b85 (from https://pypi.org/simple/uvloop/))
Reason for being yanked: <none given>
Installing collected packages: uvloop
Successfully installed uvloop-0.15.1
```

**Comment by graingert** [comment]
@1st1 it would be good to set the yanked reason, `eg Reason for being yanked: <none given>` could be "requires_python wasn't set"
