### ISSUE TITLE
Undefined symbol: _PyGen_Send

### ISSUE THREAD

**Issue by ennunpenoctal** [MagicStack/uvloop#419]
* **uvloop version**: uvloop-0.15.2
* **Python version**: 3.10.0b1
* **Platform**: Linux

Exception when importing with `from uvloop import install`

```
Traceback (most recent call last):
  File "/workspace/klaimera/klaimera.py", line 11, in <module>
    from uvloop import install
  File "/workspace/klaimera/.venv/lib/python3.10/site-packages/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
ImportError: /workspace/klaimera/.venv/lib/python3.10/site-packages/uvloop/loop.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

**Comment by ennunpenoctal** [comment]
It appears that https://github.com/MagicStack/uvloop/issues/417 addresses this. My apologies.
