### ISSUE TITLE
`Operation not permitted` while building uvloop with poetry under alpine >3.8.9 in CodeBuild

### ISSUE THREAD

**Issue by iamthen0ise** [MagicStack/uvloop#423]
* **uvloop version**: 0.15.0+
* **Python version** 3.8.10+:
* **Platform** AWS Codebuld + Apline Linux Docker:
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: No
* **Does uvloop behave differently from vanilla asyncio? How?**: Can't say exactly

Hi! 

Lately i can't build any uvloop version greater than 0.14.0 in a docker container with Apline linux image of Python 3.8.10+.

Problem persists only in Amazon CodeBuild.
Also can't replay it with local docker env.

The only working constraint is:
Python == 3.8.9
uvloop == 0.14.0

Full log is:
```
 Command ['/usr/local/bin/python', '-m', 'pip', 'install', '--no-deps', '/var/cache/pypoetry/artifacts/00/c0/58/a26191b1bfb81fed24ec5ded6e9dd26e0f42125b2a76cb8f82d653382b/uvloop-0.15.0.tar.gz'] errored with the following return code 1, and output: 
  Processing /var/cache/pypoetry/artifacts/00/c0/58/a26191b1bfb81fed24ec5ded6e9dd26e0f42125b2a76cb8f82d653382b/uvloop-0.15.0.tar.gz
  Building wheels for collected packages: uvloop
    Building wheel for uvloop (setup.py): started
    Building wheel for uvloop (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ayau35pn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ayau35pn/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-i2138uok
         cwd: /tmp/pip-req-build-ayau35pn/
    Complete output (231 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/_testbase.py -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/_version.py -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/_noop.py -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/__init__.py -> build/lib.linux-x86_64-3.8/uvloop
    running egg_info
    writing uvloop.egg-info/PKG-INFO
    writing dependency_links to uvloop.egg-info/dependency_links.txt
    writing requirements to uvloop.egg-info/requires.txt
    writing top-level names to uvloop.egg-info/top_level.txt
    reading manifest file 'uvloop.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/.git'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/docs'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/img'
    adding license file 'LICENSE-APACHE'
    adding license file 'LICENSE-MIT'
    writing manifest file 'uvloop.egg-info/SOURCES.txt'
    copying uvloop/cbhandles.pxd -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/cbhandles.pyx -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/dns.pyx -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/errors.pyx -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/loop.c -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/loop.pxd -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/loop.pyi -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/loop.pyx -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/lru.pyx -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/pseudosock.pyx -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/py.typed -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/request.pxd -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/request.pyx -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/server.pxd -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/server.pyx -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/sslproto.pxd -> build/lib.linux-x86_64-3.8/uvloop
    copying uvloop/sslproto.pyx -> build/lib.linux-x86_64-3.8/uvloop
    creating build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/async_.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/async_.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/basetransport.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/basetransport.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/check.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/check.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/handle.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/handle.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/idle.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/idle.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/pipe.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/pipe.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/poll.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/poll.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/process.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/process.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/stream.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/stream.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/streamserver.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/streamserver.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/tcp.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/tcp.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/timer.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/timer.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/udp.pxd -> build/lib.linux-x86_64-3.8/uvloop/handles
    copying uvloop/handles/udp.pyx -> build/lib.linux-x86_64-3.8/uvloop/handles
    creating build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/__init__.py -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/compat.h -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/consts.pxi -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/debug.h -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/debug.pxd -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/flowcontrol.pxd -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/fork_handler.h -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/python.pxd -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/stdlib.pxi -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/system.pxd -> build/lib.linux-x86_64-3.8/uvloop/includes
    copying uvloop/includes/uv.pxd -> build/lib.linux-x86_64-3.8/uvloop/includes
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... ./install-sh -c -d
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking whether make sets $(MAKE)... no
    checking whether make supports nested variables... no
    checking build system type... x86_64-pc-linux-musl
    checking host system type... x86_64-pc-linux-musl
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for style of include used by make... none
    checking dependency style of gcc... none
    checking for gcc way to treat warnings as errors... -Werror
    checking if gcc supports -fvisibility=hidden... yes
    checking if gcc supports -g flag... yes
    checking if gcc supports -std=gnu89 flag... yes
    checking if gcc supports -Wall flag... yes
    checking if gcc supports -Wextra flag... yes
    checking if gcc supports -Wno-long-long flag... yes
    checking if gcc supports -Wno-unused-parameter flag... yes
    checking if gcc supports -Wstrict-prototypes flag... yes
    checking for ar... ar
    checking the archiver (ar) interface... ar
    checking how to print strings... printf
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/x86_64-alpine-linux-musl/bin/ld
    checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 98304
    checking how to convert x86_64-pc-linux-musl file names to x86_64-pc-linux-musl format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-musl file names to toolchain format... func_convert_file_noop
    checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking whether make supports nested variables... (cached) no
    checking whether gcc is Clang... no
    checking whether pthreads work with -pthread... yes
    checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
    checking whether more special flags are required for pthreads... no
    checking for PTHREAD_PRIO_INHERIT... yes
    checking for dlopen in -ldl... yes
    checking for library containing kstat_lookup... no
    checking for library containing gethostbyname... none required
    checking for library containing perfstat_cpu... no
    checking for library containing clock_gettime... none required
    checking for library containing sendfile... none required
    checking for library containing socket... none required
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking sys/ahafs_evProds.h usability... no
    checking sys/ahafs_evProds.h presence... no
    checking for sys/ahafs_evProds.h... no
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating libuv.pc
    config.status: executing depfiles commands
    config.status: executing libtool commands
    make: ./install-sh: Operation not permitted
    make: *** [Makefile:1308: src/.dirstamp] Error 127
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ayau35pn/setup.py", line 283, in <module>
        setup(
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
        self.run_command('build')
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-req-build-ayau35pn/setup.py", line 242, in build_extensions
        self.build_libuv()
      File "/tmp/pip-req-build-ayau35pn/setup.py", line 227, in build_libuv
        subprocess.run(
      File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['make', '-j8', 'CFLAGS= -O2 -fPIC ']' returned non-zero exit status 2.
    ----------------------------------------
    ERROR: Failed building wheel for uvloop
    Running setup.py clean for uvloop
  Failed to build uvloop
  Installing collected packages: uvloop
      Running setup.py install for uvloop: started
      Running setup.py install for uvloop: finished with status 'error'
```

Sorry if i missed something. Feel free to ask details.
Thank you!

**Comment by Woile** [comment]
I'm having the same issue with this make command:
```
subprocess.CalledProcessError: Command '['make', '-j1', 'CFLAGS= -O2 -fPIC ']' returned non-zero exit status 2
```

I've tried python 3.9 and 3.7
uvloop (uvloop>=0.14.0,!=0.15.0,!=0.15.1;) as a dependency of uvicorn 0.14.0

were you able to solve this?

**Comment by iamthen0ise** [comment]
> I'm having the same issue with this make command:
> 
> ```
> 
> subprocess.CalledProcessError: Command '['make', '-j1', 'CFLAGS= -O2 -fPIC ']' returned non-zero exit status 2
> 
> ```
> 
> 
> 
> I've tried python 3.9 and 3.7
> 
> uvloop (uvloop>=0.14.0,!=0.15.0,!=0.15.1;) as a dependency of uvicorn 0.14.0
> 
> 
> 
> were you able to solve this?

No, unfortunately. Had to pin Python to 3.8.9, and uvloop to 0.14.0 to make it work.

**Comment by Woile** [comment]
I had an old version of docker `18.09.3`, upgrading to `20.10.8` solved the issue.
I'm using python `3.9` and uvloop `0.16.0`.

This comment helped me: https://github.com/MagicStack/uvloop/issues/247#issuecomment-871439788

**Comment by iamthen0ise** [comment]
@Woile Thank you very much! Will try!

**Comment by iamthen0ise** [comment]
So, looks like it is not an uvloop problem, let me close the issue.
