### ISSUE TITLE
0.15.3: setuptools `build_sphinx` command fails

### ISSUE THREAD

**Issue by kloczek** [MagicStack/uvloop#430]
* **uvloop version**: 0.15.3
* **Python version**: 3.8.11
* **Platform**: Linux/x86_64

Looks like `version` is not present in setup.py
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.1.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/uvloop-0.15.3/docs/conf.py", line 14, in <module>
    raise RuntimeError('unable to read the version from setup.py')
```

**Comment by kloczek** [comment]
This ticket can be closed as using `setup.py` is now deprecated.
