### ISSUE TITLE
No module named 'uvloop.loop'

### ISSUE THREAD

**Issue by tufbel** [MagicStack/uvloop#462]
My Linux `uname -a` output is `Linux ***** #1 SMP PREEMPT Wed Sep 8 10:41:11 UTC 2021 armv7l armv7l armv7l GNU/Linux`
```python
>>> import uvloop
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/cowave/lib/python_lib/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
ModuleNotFoundError: No module named 'uvloop.loop'
```

**Comment by Ancieg** [comment]
Have the same issue.

uvloop built from tag: v0.16.0
Python version: 3.10.6
Cython version: 0.29.32
libuv version: 1.14.2 (system)

**Comment by tufbel** [comment]
> > Have the same issue.
> > uvloop built from tag: v0.16.0
> > Python version: 3.10.6
> > Cython version: 0.29.32
> > libuv version: 1.14.2 (system)
> 
> Tried to build with `--inplace` and it worked.

Thanks, is the build done in Arm's Python using setup.py?
