### ISSUE TITLE
unable to perform operation on <WriteUnixTransport closed=True reading=False 0x7f16825f8ba0

### ISSUE THREAD

**Issue by m0hammadhossein** [MagicStack/uvloop#506]
* **uvloop version**: 0.17.0
* **Python version**: 3.10.7
* **Platform**: ubuntu 20.04
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: yes
* **Does uvloop behave differently from vanilla asyncio? How?**: yes

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pytgcalls/methods/groups/join_group_call.py", line 275, in internal_sender
    await self._binding.send(request)
  File "/usr/local/lib/python3.10/dist-packages/pytgcalls/binding.py", line 212, in send
    await self._send({
  File "/usr/local/lib/python3.10/dist-packages/pytgcalls/binding.py", line 221, in _send
    self._js_process.stdin.write(
  File "/usr/lib/python3.10/asyncio/streams.py", line 326, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <WriteUnixTransport closed=True reading=False 0x7f16825f8ba0>; the handler is closed

```

**Comment by kekekekule** [comment]
got the same issue with 0.16

**Comment by andrmueller** [comment]
got the issue when using aiomysql, probably the [issue](https://github.com/aio-libs/aiomysql/issues/966) people are facing with aiomysql and uvloop seems to be related to this issue here.

Maybe the information posted in the aiomysql issue helps if someone takes this over.

**Comment by Kludex** [comment]
@1st1 We talked at PyCon US this year. 👋 I said I would create an issue about it... The issue is this one.

Let me share an MRE:

```py
import asyncio


class EchoServerProtocol(asyncio.Protocol):
    def connection_made(self, transport: asyncio.Transport):  # type: ignore
        self.transport = transport

    def data_received(self, data: bytes):
        message = data.decode()
        print("Data received: {!r}".format(message))

        self.transport.close()

        # We introduce a short wait to ensure closure processing
        asyncio.ensure_future(self.write_after_closure(data))

    async def write_after_closure(self, data: bytes):
        print(self.transport)
        # uvloop: <TCPTransport closed=True reading=False 0x153e33aa0>
        # asyncio: <_SelectorSocketTransport closed fd=7>

        self.transport.write(data)
        # uvloop: RuntimeError
        # asyncio: no error

    def connection_lost(self, exc: Exception | None):
        print("The client connection lost")


async def main():
    loop = asyncio.get_running_loop()

    server = await loop.create_server(EchoServerProtocol, "127.0.0.1", 8888)

    async with server:
        await server.serve_forever()


# import uvloop
# asyncio.run(main(), loop_factory=uvloop.new_event_loop, debug=True)

asyncio.run(main())
```
Uncomment the lines above to see the difference in behavior.

You can use any client to call `http://127.0.0.1:8888`.

You can also use this small client script, if you want to try things as well...

```py
import asyncio


async def tcp_echo_client(message: str):
    reader, writer = await asyncio.open_connection("127.0.0.1", 8888)

    print(f"Send: {message!r}")
    writer.write(message.encode())

    data = await reader.read(100)
    print(f"Received: {data.decode()!r}")

    print("Close the connection")
    writer.close()
    await writer.wait_closed()


asyncio.run(tcp_echo_client("Hello, World!"))
```

cc @fantix for visibility.
