### ISSUE TITLE
uvloop pypy3.9 error on import

### ISSUE THREAD

**Issue by owenwastaken** [MagicStack/uvloop#521]
* **uvloop version**: 0.17.0
* **Python version**: pypy3.9
* **Platform**: Debian Bullseye
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Yes
* **Does uvloop behave differently from vanilla asyncio? How?**: Vanilla asyncio does not create this error

uvloop fails to import with the following traceback
```Traceback (most recent call last):
  File "/var/gpob/GB.py", line 36, in <module>
    import uvloop
  File "/usr/lib/pypy3.9/site-packages/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
ImportError: /usr/lib/pypy3.9/site-packages/uvloop/loop.pypy39-pp73-x86_64-linux-gnu.so: undefined symbol: PyContext_CopyCurrent```

**Comment by chrysn** [comment]
This is probably a duplicate of https://github.com/MagicStack/uvloop/issues/537 -- and while this is the older item, over there is where some conversation has already accumulated.
