### ISSUE TITLE
Add support for loop.sock_sendto

### ISSUE THREAD

**Issue by difeid** [MagicStack/uvloop#561]
* **uvloop version**: 0.17.0
* **Python version**: 3.11.4
* **Platform**: Linux
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Not a bug
* **Does uvloop behave differently from vanilla asyncio? How?**: Yes, not implemented feature

The uvloop not implement method [sock_sendto](https://docs.python.org/3/library/socket.html#socket.socket.sendto).
> coroutine loop.sock_sendto(sock, data, address)
> Send a datagram from sock to address. Asynchronous version of socket.sendto()
> 
> Return the number of bytes sent.
> sock must be a non-blocking socket.
> New in version 3.11.

The simple test case that reproduces the problem:
```
#!/usr/bin/env python3

import socket
import asyncio
import uvloop

uvloop.install()

addr = ("127.0.0.1", 1111)
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.setblocking(False)

loop = asyncio.get_event_loop()
loop.run_until_complete(loop.sock_sendto(s, b'test', addr))
```

uvloop == 0.17.0 response:
```
Traceback (most recent call last):
  File "/home/danil/test_async_sock.py", line 16, in <module>
    loop.run_until_complete(loop.sock_sendto(s, b'test', addr))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 2629, in sock_sendto
  NotImplementedError
  ```

**Comment by WilliamOConnell** [comment]
I had a similar issue with `sock_recvfrom`. It took me a while to figure out what was going on because I was using Sanic and hadn't actually heard of `uvloop`. I got around it by disabling it in the Sanic config but it would be nice if these methods could be implemented.

**Comment by KaylaSolace** [comment]
sad to see this still isnt supported.

**Comment by tarasko** [comment]
Hey guys, @aldem @KaylaSolace @difeid 

[aiofastnet](https://github.com/tarasko/aiofastnet) provides drop-in implementations for `sock_recvfrom`, `sock_recvfrom_into`, `sock_sendto`.

Depending on you project, you can use them either directly: 
```
    data = await aiofastnet.recvfrom(asyncio.get_running_loop(), sock, 64*1024) 
```

or just patch the current loop (which can be uvloop)
```
    aiofastnet.patch_loop()
    ...
    data = await asyncio.get_running_loop().recvfrom(sock, 64*1024) 
```
