### ISSUE TITLE
aiohttp.worker.GunicornUVLoopWebWorker + unix sockets Nginx - error

### ISSUE THREAD

**Issue by Dexus77** [MagicStack/uvloop#59]
- **uvloop version**: 0.5.4
- **python version**: 3.5.2
- **platform**: Centos7

Aiohttp recomended deploy Gunicorn + Nginx
Gunicorn (aiohttp.worker.GunicornWebWorker) + unix socket Nginx - OK
Ginicorn (aiohttp.worker.GunicornUVLoopWebWorker) + unix sockets Nginx - error

Traceback (most recent call last):
  File "/usr/local/python/3.5.2/lib/python3.5/site-packages/aiohttp/helpers.py", line 407, in log
    [message, environ, response, transport, time]))
  File "/usr/local/python/3.5.2/lib/python3.5/site-packages/aiohttp/helpers.py", line 394, in _format_line
    return tuple(m(args) for m in self._methods)
  File "/usr/local/python/3.5.2/lib/python3.5/site-packages/aiohttp/helpers.py", line 394, in <genexpr>
    return tuple(m(args) for m in self._methods)
  File "/usr/local/python/3.5.2/lib/python3.5/site-packages/aiohttp/helpers.py", line 347, in _format_a
    peername = args[3].get_extra_info('peername')
  File "uvloop/handles/tcp.pyx", line 150, in uvloop.loop.TCPTransport.get_extra_info (uvloop/loop.c:66876)
  File "uvloop/dns.pyx", line 60, in uvloop.loop.__convert_sockaddr_to_pyaddr (uvloop/loop.c:82997)
RuntimeError: cannot convert sockaddr into Python object

**Comment by 1st1** [comment]
I'll need some details on this:

* What kind of socket connection is the transport working with?  I.e. this exception can only be triggered if the socket is not `AF_INET` or `AF_INET6`.

* Can you provide the source code that exhibits the problem?

* Were you able to reproduce this on other OSes?

**Comment by Dexus77** [comment]
1. Yes, the problem is when connect via unix socket.
2. Test add. Main config Nginx - default.
3. Sorry, no other OS.

[testapp.zip](https://github.com/MagicStack/uvloop/files/554191/testapp.zip)

**Comment by 1st1** [comment]
Seems that somehow gunicorn or aiohttp bind UNIX address using a TCP server (`loop.create_server`, instead of `loop.create_unix_server`).

@asvetlov Do you have any idea what's going on?

**Comment by 1st1** [comment]
Ah, I got it: https://github.com/python/asyncio/pull/453

**Comment by 1st1** [comment]
This should be fixed in aiohttp `1.1.2` and uvloop `0.6.1`. Feel free to reopen if anything.
