### ISSUE TITLE
sys.exit(...) exception catched by uvloop

### ISSUE THREAD

**Issue by dmoklaf** [MagicStack/uvloop#612]
* **uvloop version**:
0.19.0

* **Python version**:
3.11.9

* **Platform**:
MacOS 14.5 (Sonoma)
mamba 1.5.8
conda 24.5.0

* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:
Not yet

* **Does uvloop behave differently from vanilla asyncio? How?**:
I have never had this bug with vanilla asyncio however.

If a sys.exit(...) call is made while uvloop is being used in coroutines (in my case, through aiohttp crawling of web URLs), uvloop may catch the SystemExit exception, and not let it bubble as a SystemExit to the top of the application. Instead, it logs this at the ERROR level:
```
2024-07-26 06:25:06,802 ERROR asyncio Fatal error on transport TCPTransport
protocol: <uvloop.loop.SSLProtocol object at 0x16b54de80>
transport: <TCPTransport closed=False reading=False 0x1693bfff0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 1007, in uvloop.loop.__uv_stream_buffered_on_read
  File "uvloop/loop.pyx", line 109, in uvloop.loop.run_in_context1
  File "uvloop/sslproto.pyx", line 382, in uvloop.loop.SSLProtocol.buffer_updated
  File "uvloop/sslproto.pyx", line 711, in uvloop.loop.SSLProtocol._do_read
  File "uvloop/sslproto.pyx", line 776, in uvloop.loop.SSLProtocol._do_read__copied
  File "/opt/homebrew/Caskroom/miniforge/base/envs/work/lib/python3.11/ssl.py", line 912, in read
    def read(self, len=1024, buffer=None):
    
  File "/Users/dmoklaf/Local/metax/python_libraries/application.py", line 171, in _exit
    sys.exit(code)
SystemExit: 1
```

Indeed, a quick look at the uvloop code shows that it logs the SystemExit exception, as SystemExit does not subclass OSError:
https://github.com/MagicStack/uvloop/blob/6c770dc3fbdd281d15c2ad46588c139696f9269c/uvloop/handles/basetransport.pyx#L40
PS: there also seems to be other _fatal_error implementations in uvloop, I am not completely sure if these other places do not suffer from the same issue

And it also swallows the SystemExit exception, instead of propagating it upward as requested by the Python specification.

**Comment by rgeronimi** [comment]
This is a pretty serious issue that sometimes freezes our python server. We are facing the decision to drop using uvloop. Is it intended to be fixed or not? Thx

**Comment by fantix** [comment]
Sorry for the delay! Yeah, this would be an important issue to fix. I tried some simple `sys.exit()` calls in `async def main()`, `create_task()` and `call_soon()` (both 0.19.0 and latest master), but none of those reproduced the issue. I'd appreciate it if you could provide a short code snippet to reproduce it. Also, please try with newer versions of uvloop.
