### ISSUE TITLE
What is happens with  CancelledError?

### ISSUE THREAD

**Issue by msean** [MagicStack/uvloop#67]
* **uvloop version**: 0.6.7
* **python version**:3.5.0
* **platform**:centos

I deployed my project on sanic(based on vuloop) frame,managered four process with supervisor,used nginx as a http proxy.I did a stress test with ab,some requests got 200 response,but some requests failed,In my log,the error message about the statck is below:
```
Traceback (most recent call last):
File "/home/mwh/ad_sanic/handlers/oprs.py", line 17, in post
   _parsed_req = await ReqParser(_req_body,'parse',req_ip=(request.headers['Remote-Addr']).split(':')[0]).parser()
File "/home/mwh/ad_sanic/utils/req_parse.py", line 49, in parser
   _mapped['sim_country_iso'] = await self.geo()
File "/home/mwh/ad_sanic/utils/req_parse.py", line 75, in geo
    db_country = (await self.db.get(DbIp.select(DbIp.country).where((DbIp.ip_from<=self._req_ip)&(DbIp.ip_to>=self._req_ip)))).country
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/peewee_async.py", line 169, in get
    result = yield from self.execute(query.limit(1))
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/peewee_async.py", line 269, in execute
    return (yield from execute(query))
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/peewee_async.py", line 428, in execute
    return (yield from coroutine(query))
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/peewee_async.py", line 569, in select
    cursor = yield from _execute_query_async(query)
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/peewee_async.py", line 1491, in _execute_query_async
    return (yield from _run_sql(query.database, *query.sql()))
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/peewee_async.py", line 1476, in _run_sql
    cursor = yield from database.cursor_async()
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/peewee_async.py", line 902, in cursor_async
    return (yield from self._async_conn.cursor(conn=conn))
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/peewee_async.py", line 1067, in cursor
    conn = yield from self.acquire()
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/peewee_async.py", line 1036, in acquire
    return (yield from self.pool.acquire())
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/aiopg/utils.py", line 67, in __iter__
    resp = yield from self._coro
File "/home/mwh/py3.5_virtuanlenv/lib/python3.5/site-packages/aiopg/pool.py", line 180, in _acquire
    yield from self._cond.wait()
File "/usr/local/lib/python3.5/asyncio/locks.py", line 326, in wait
    yield from fut
File "/usr/local/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
File "uvloop/future.pyx", line 434, in uvloop.loop.BaseTask._fast_wakeup           (uvloop/loop.c:112710)
File "/usr/local/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError
```
What's wrong with it ?

**Comment by asvetlov** [comment]
I believe the issue is not related to uvloop. 
Raise the question on sanic's bugtracker.

**Comment by 1st1** [comment]
Yes, `CancelledError` is a normal thing to occur. Most likely this has to be properly handled in Sanic.  Please report this issue on their tracker, and please reopen if this turns out to be a uvloop bug.
